name: my_health_journal
description: A new Flutter project.
publish_to: 'none' 
version: 1.0.0+1

environment:
  sdk: '>=3.0.5 <4.0.0'
dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  firebase_core: ^2.15.0
  firebase_auth: ^4.7.2
  cloud_firestore: ^4.8.4
  intl: ^0.18.1
  fl_chart: ^0.63.0
  table_calendar: ^3.0.9

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true

  fonts:
    - family: Rubik
      fonts:
        - asset: Assets/fonts/Rubik-Medium.ttf
          style: normal
        - asset: Assets/fonts/Rubik-Bold.ttf
          weight: 700
        - asset: Assets/fonts/Rubik-BoldItalic.ttf
          style: italic
          weight: 700
        - asset: Assets/fonts/Rubik-Italic.ttf
          style: italic
