// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAPKN_cgBDubQS-bkhUS5FhZ1WTiModBN4',
    appId: '1:745747806049:web:7d665d28e73822bd443720',
    messagingSenderId: '745747806049',
    projectId: 'myhealthjournal-576f3',
    authDomain: 'myhealthjournal-576f3.firebaseapp.com',
    storageBucket: 'myhealthjournal-576f3.appspot.com',
    measurementId: 'G-GZRQESBGRJ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBkPniTeAbCgATr49m7m5JXA9vsctuz_N8',
    appId: '1:745747806049:android:989602aee9609dd5443720',
    messagingSenderId: '745747806049',
    projectId: 'myhealthjournal-576f3',
    storageBucket: 'myhealthjournal-576f3.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAioNaImq5Ypg7nYOtVF27P4f49gcg_XcI',
    appId: '1:745747806049:ios:7bed9ced31ac36b7443720',
    messagingSenderId: '745747806049',
    projectId: 'myhealthjournal-576f3',
    storageBucket: 'myhealthjournal-576f3.appspot.com',
    iosClientId: '745747806049-ik0ol5920qm2qsh4o9rvvrar08m3trju.apps.googleusercontent.com',
    iosBundleId: 'com.gregperoutka.myHealthJournal',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAioNaImq5Ypg7nYOtVF27P4f49gcg_XcI',
    appId: '1:745747806049:ios:c31292d73a89eb17443720',
    messagingSenderId: '745747806049',
    projectId: 'myhealthjournal-576f3',
    storageBucket: 'myhealthjournal-576f3.appspot.com',
    iosClientId: '745747806049-nivnvcn1412rf83am9ttbjjns1amq4bq.apps.googleusercontent.com',
    iosBundleId: 'com.gregperoutka.myHealthJournal.RunnerTests',
  );
}
